Feature: Generate report
  Description: A project leader or employee generates a report of the current activities in a project
  User: Employee

  Background:
    Given a project
    And an employee
# DOESNT MAKE SENSE TO DO THIS, IT IS COVERED IN get_project_hours
#  Scenario: Report generated by project leader
#    Given employee is the leader of the project
#    When the employee generates a report
#    Then a report is generated

#  Scenario: Report generated of project without a project leader
#    Given employee is not the leader of the project
#    When the employee generates a report
#    Then a report is generated

#  Scenario: Report generated by different employee than project leader
#    Given employee is not the leader of the project
#    And the project leader is "Hans"
#    When the employee generates a report
#    Then error message "You are not the project leader of this project" is given
